# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DAWM
email: aavendan@espol.edu.ec
description: > # this means to ignore newlines until "baseurl:"
  Este curso provee a los estudiantes del conocimiento y de la experiencia práctica 
  para diseñar e implementar aplicaciones web y móviles cumpliendo con los estándares 
  actuales y las buenas prácticas de programación que faciliten su mantenibilidad, 
  escalabilidad y adaptabilidad. En el curso se diseñan y modelan aplicaciones que 
  realizan requerimientos web asincrónicos entre el cliente y el servidor para mejorar 
  la experiencia de usuario. Además, se utiliza el patrón de diseño de arquitectura 
  modelo-vista-controlador en la programación en el servidor y en el cliente para separar 
  la lógica del negocio de la interfaz de usuario, permitiendo un fácil mantenimiento 
  de la aplicaciones desarrolladas. Finalmente, en el curso se manejan conceptos 
  independientes de la plataforma web utilizada, por lo que facilita el aprendizaje 
  autónomo de nuevas tecnologías y entornos de trabajo.
baseurl: "/DAWM"
url: "https://dawfiec.github.io/"

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

