# Generated by Django 3.0.2 on 2020-08-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('acceso', models.IntegerField(default=0)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('acceso', models.IntegerField(default=0)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.Facultad')),
            ],
        ),
    ]
